[package]
version = "0.1.0"
name = "pixade"
authors = ["milan <milan@milan.wtf>"]
edition = "2021"
description = "A modern LED arcade."

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.14", features = ["wayland"] }
